# Generated by Django 3.1.5 on 2021-01-31 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.CharField(choices=[('AC', 'Ac'), ('LVDC', 'Lvdc')], max_length=10)),
                ('length', models.FloatField(help_text='Length of connection in meters')),
                ('power', models.FloatField(help_text='Power handling capability in watts')),
                ('typical_efficiency', models.FloatField(help_text='Typical efficiency in the range [0,1)')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
                ('power_source', models.CharField(choices=[('SOLAR', 'Solar'), ('WIND', 'Wind')], max_length=10)),
                ('max_power', models.FloatField(help_text='Maximum power in watts')),
                ('max_voltage', models.FloatField(help_text='Maximum voltage in volts')),
                ('consumers', models.ManyToManyField(through='stats.PowerTransfer', to='stats.Consumer')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.plant')),
            ],
        ),
        migrations.AddField(
            model_name='powertransfer',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.producer'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.plant'),
        ),
    ]
