# Generated by Django 3.1.5 on 2021-05-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_productionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionhistory',
            name='time_period',
            field=models.CharField(choices=[('year', 'Year'), ('month', 'Month'), ('week', 'Week'), ('day', 'Day'), ('hour', 'Hour')], default='year', max_length=6),
            preserve_default=False,
        ),
    ]
