# Generated by Django 3.1.5 on 2021-05-16 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_productionhistory_time_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionhistory',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
